### PR TITLE
[Enhancement] 5 New Images

### PR DESCRIPTION
**Pull request by Evilscaught**
**_Action_**
Requesting to merge `Evilscaught/presearch-homepage-backgrounds::main` into `PresearchOfficial/presearch-homepage-backgrounds::main` 

**_Description_**
Adds four new images:
- Temple of Bachus, Heliopolis, Lebanon
- Defenseurs de la Patrie, Lyon, France
- Passerelle de l'Homme sur la Saône, Lyon, France
- St-a Gertrud, Stockholm, Sweden

**_Question_**
Should an standard specifying what keys can be used in the JSON files be added to the README.md? 
https://exiv2.org/tags.html

**_Images_**
## Defenseurs de la Patrie, Lyon, France
defenseurs-de-la patrie

## Passerelle de l'Homme sur la Saône, Lyon, France
passerelle-de-lhomme-de-la-roche-rèverse

## Temple of Bachus, Heliopolis, Lebanon
temple-of-bachus

## St-a Gertrud, Stockholm, Sweden
s-ta-gertrud

### CODE REVIEW

**Comment by jejopl** [comment]
Hey @Evilscaught, thanks for your submission!

There's one issue, the image size must not be larger than 512kb.
Also, we have changed the structure of the metadata and now, the categories key also is required

Step 4 on the instruction
https://github.com/PresearchOfficial/presearch-homepage-backgrounds

**Comment by Evilscaught** [comment]
Thanks, I'll re-open it once I've applied your feedback!

**Comment by Evilscaught** [comment]
@jejopl 
Took a while but finally got around to doing it.  All my images have been compressed to be less than 512 kb, and I've added a category key to their respective json files. 🎉

**Comment by Evilscaught** [comment]
# Decommissioned Repository. Closing Pull Request.

**Pull request closed without merging**
